### ISSUE TITLE
Not sure best way to contact you

### ISSUE THREAD

**Issue by acedrew** [anedward01/tpm2KeyUnlock#3]
Hey there, this is a really interesting project. I read somewhere in issues or comments that you were graduating this year, not sure what your plans are or how the job market is, but I would be interested in contracting you to develop this out further and enabling more automation to the process.
I'm andrew@aceiotsolutions.com if you're interested.

Andrew

**Comment by anedward01** [comment]
I have sent you an email with contact info. I look forward to hearing from you.

**Comment by anedward01** [comment]
If you prefer to contact me, my email is [edward.anguiano@edwardssite.com](mailto:edward.anguiano@edwardssite.com)
